package main

import (
	"fmt"
	"log"

	"bome-backend/internal/config"
	"bome-backend/internal/database"

	_ "github.com/lib/pq"
)

func main() {
	// Load configuration
	cfg := config.New()

	// Connect to database
	db, err := database.New(cfg)
	if err != nil {
		log.Fatal("Failed to connect to database:", err)
	}
	defer db.Close()

	// Real video data from your Bunny library
	bunnyVideoID := "6b791971-9622-4a4a-bad1-b117cec0445c"
	title := "Road to Bali (1952)"
	description := "Classic 1952 film starring Bing Crosby, Bob Hope, and Dorothy Lamour. A real video from your Bunny.net library for testing the integration."
	category := "Classic Films"
	duration := 5467               // seconds from Bunny API
	fileSize := int64(12926956478) // bytes from Bunny API

	// Tags for the video
	tags := []string{"classic", "1952", "comedy", "adventure", "bing crosby", "bob hope", "dorothy lamour"}

	// Admin user ID (assuming super admin)
	userID := 4

	// Create video record
	video, err := db.CreateVideo(
		title,
		description,
		bunnyVideoID,
		"", // thumbnail URL will be generated by Bunny service
		category,
		duration,
		fileSize,
		tags,
		userID,
	)
	if err != nil {
		log.Fatal("Failed to create video:", err)
	}

	// Update video status to "ready" (even though Bunny shows error, we'll try it)
	_, err = db.Exec(
		"UPDATE videos SET status = 'ready', updated_at = NOW() WHERE id = $1",
		video.ID,
	)
	if err != nil {
		log.Fatal("Failed to update video status:", err)
	}

	fmt.Printf("✅ Successfully added Bunny video to database!\n\n")
	fmt.Printf("Database Video ID: %d\n", video.ID)
	fmt.Printf("Bunny Video ID: %s\n", video.BunnyVideoID)
	fmt.Printf("Title: %s\n", video.Title)
	fmt.Printf("Description: %s\n", video.Description)
	fmt.Printf("Category: %s\n", video.Category)
	fmt.Printf("Duration: %d seconds (%.1f minutes)\n", video.Duration, float64(video.Duration)/60)
	fmt.Printf("File Size: %d bytes (%.2f GB)\n", video.FileSize, float64(video.FileSize)/(1024*1024*1024))
	fmt.Printf("Tags: %v\n", tags)
	fmt.Printf("Status: ready\n")
	fmt.Printf("Created: %s\n", video.CreatedAt.Format("2006-01-02 15:04:05"))
	fmt.Printf("\n")
	fmt.Printf("🎬 Your frontend should now display this real Bunny.net video!\n")
	fmt.Printf("📺 Video URL will be: https://iframe.mediadelivery.net/embed/464044/%s\n", bunnyVideoID)
	fmt.Printf("🔗 API endpoint: http://localhost:8080/api/v1/videos\n")
}
